In [ ]:
Задание 1

Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

если источник traffic_source равен yandex или google, то в source_type ставится organic
для источников paid и email из России - ставим ad
для источников paid и email не из России - ставим other
все остальные варианты берем из traffic_source без изменений

In [1]:
import pandas as pd

log = pd.read_csv('visit_log.csv', sep=';')

def source_type(log):
    if (log.traffic_source == 'yandex') | (log.traffic_source == 'google'):
        return 'organic'
            
    elif ((log.traffic_source == 'paid') | (log.traffic_source == 'email')) & (log.region == 'Russia'):
        return 'ad'
        
    elif ((log.traffic_source == 'paid') | (log.traffic_source == 'email')) & (log.region != 'Russia'):
        return 'other'
    
    return log['traffic_source']
    
    
log['source_type'] = log.apply(source_type, axis = 1)
log.head(20)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,direct
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,direct
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
10,1549980777,01d448afd9,https://host.ru/a5dda93e70318570c0,India,27e76a4a80,direct,direct
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,organic
12,1549980789,15ec7bf0b5,https://host.ru/8e88d4703848cc0ec4,Russia,6d1d81f7f8,paid,ad
13,1549980792,dd46c3eebb,https://host.ru/3004a8273caeef2867,China,7e301c8c41,direct,direct
14,1549980793,e7ecebbc59,https://host.ru/05e41944dd85a900a6,Belarus,ac52dedc3b,direct,direct
15,1549980797,5322fecfc9,https://host.ru/4adc8a29b212051b04,Belarus,9a45d98867,paid,other
16,1549980801,374708fff7,https://host.ru/39fa884393666d45fc,Russia,e9bd59e22d,google,organic
17,1549980807,0a88111852,https://host.ru/2fcb223266880ccf57,Ukraine,a2ba8fa3db,paid,other
18,1549980814,60daa3a5f7,https://host.ru/ef57543002ce2a0f2a,Belarus,72cb10fb5c,direct,direct
19,1549980816,d6fd62f5ce,https://host.ru/f1eb4601740d627ab0,Belarus,7269dcd869,direct,direct

In [ ]:
Задание 2

В файле URLs.txt содержатся url страниц новостного сайта. 
Вам необходимо отфильтровать его по адресам страниц с текстами новостей.
Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, 
затем 8 цифр, затем дефис. Выполните следующие действия:

1. Прочитайте содержимое файла с датафрейм
2. Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение 
в соответствии с заданным шаблоном

In [1]:
txt = pd.read_csv('URLs.txt')
txt.loc[txt.url.str.contains(r'/\d{8}\-')].head(50)

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
10  /middleeast/36131117-divizion-s-400-ne-zametil...
11  /economics/36065674-rossiyane-vozmutilis-minim...
12  /politics/36118047-otets-24-detey-potreboval-i...
13  /travel/36194479-v-sheremetevo-passazhiry-ustr...
14  /politics/35638742-nesolidno-mariya-zaharova-s...
15  /video/36012692-tramp-otkrestilsya-ot-rossii-i...
16     /starlife/36174817-guzeeva-rasstalas-s-muzhem/
17  /health/36149308-predlozheno-prostoe-sredstvo-...
18  /science/36139723-set-vzbudorazhila-novost-o-s...
19  /cis/36229699-poroshenko-obyavil-vseukrainskiy...
20  /incidents/36225203-tonnel-obrushilsya-v-novoy...
21  /politics/36118047-otets-24-detey-potreboval-i...
22  /world/36075956-na-granitse-s-krymom-zahvachen...
23  /politics/36115220-mid-vystupil-s-preduprezhde...
24  /world/36018565-sbu-opublikovala-zapis-peregov...
25  /politics/36150505-stala-izvestna-prichina-sme...
26  /middleeast/36131117-divizion-s-400-ne-zametil...
27  /sport/36055585-fiyon-maye-my-prouchili-russki...
28  /crazy-world/36193471-seks-bezhentsy-vernulis-...
29  /crazy-world/36087352-moskvicha-shokirovala-na...
30  /incidents/36096689-rossiyskih-turistov-dvazhd...
31  /video/36225009-otschet-poshel-zaharchenko-naz...
33  /health/36139780-opredelen-reshayuschiy-faktor...
35  /business/36187789-v-rf-hotyat-povysit-nalogi-...
36  /video/35930625-dozvonivshiysya-v-efir-ukrains...
38  /head/36214416-u-zheny-karachentsova-nashli-al...
40  /head/36038043-foto-otdyhayuschiy-obama-vzbudo...
41  /cis/36189830-kiev-arestoval-imuschestvo-v-krymu/
42  /video/36006794-pogibshaya-melamed-ostavila-pr...
43  /video/36082961-nikol-kidman-prishla-na-britan...
44  /incidents/36173928-v-ekaterinburge-migranty-u...
45             /video/36151719-petrosyanu-grozit-sud/
46  /business/36102731-rubl-rezko-otreagiroval-na-...
47   /articles/36193368-donbass-reshil-udarit-pervym/
48  /science/36178249-rasshifrovano-predskazanie-n...
49  /world/36206871-na-ukraine-nachalsya-shturm-uc...
50  /science/36233829-sozdano-lekarstvo-ot-vseh-vi...
51  /politics/36093799-sbezhavshuyu-iz-rossii-maks...
52  /cis/36144647-v-tsentr-kieva-styagivayut-voenn...
53  /starlife/36140271-skandalnoe-foto-britni-spir...
54  /finances/36043911-rublyu-predrekli-dvoynoy-udar/
55  /starlife/36135554-doch-valerii-snyalas-v-otkr...
56  /starlife/36005664-dzhennifer-lopes-vzorvala-i...
57    /starlife/36240935-dzhigurde-postavili-diagnoz/
58  /politics/36233197-times-britaniya-peregnula-p...

In [ ]:
Задание 3

Используйте файл с оценками фильмов ml-latest-small/ratings.csv. Посчитайте среднее время жизни пользователей,
которые выставили более 100 оценок.
Под временем жизни понимается разница между максимальным и минимальным значением столбца timestamp для данного значения userId.

In [18]:
ratings = pd.read_csv('ratings.csv', sep=',')    #импорт
ratings['timestamp'] = pd.to_datetime(ratings['timestamp'],unit='s')   # преобразование времени в понятный формат
ts_max = ratings.groupby(['userId']).agg({'timestamp': 'max'})    # определяю максимальное 
ts_min = ratings.groupby(['userId']).agg({'timestamp': 'min'})    # и минимальное время выставления оценок
ts = ts_max.merge(ts_min, on = 'userId', how = 'inner', suffixes=('_max', '_min'))    # объединяю макс и мин время 
ts['difference'] = ts['timestamp_max'] - ts['timestamp_min']    # считаю "время жизни" всех пользователей
rating_cnt = ratings.groupby(['userId']).count()    # группирую пользователей по количеству оценок
ratings_qry = rating_cnt[['rating']].query('rating > 100')    # оставляю тех, у кого больше 100 оценок
average_ttl = ts.merge(ratings_qry, on = 'userId', how = 'inner')    # объединяю "время жизни" и юзеров с >100 оценок
average_ttl['difference']    # вывожу нужный столбец с инфой

userId
4        2 days 08:32:40
8        0 days 23:39:47
15    5455 days 22:38:16
17       0 days 02:14:13
19       0 days 01:28:02
             ...
656      0 days 00:50:53
659    365 days 20:23:31
664   1136 days 08:20:39
665    626 days 12:31:11
671    130 days 14:26:24
Name: difference, Length: 258, dtype: timedelta64[ns]

In [ ]:
Задание 4

Дана статистика услуг перевозок клиентов компании по типам
Необходимо сформировать две таблицы:
таблицу с тремя типами выручки для каждого client_id без указания адреса клиента
аналогичную таблицу по типам выручки с указанием адреса клиента

Дана статистика услуг перевозок клиентов компании по типам:

rzd - железнодорожные перевозки
auto - автомобильные перевозки
air - воздушные перевозки
client_base - адреса клиентов

In [27]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)

auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)

air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)

client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1', 
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)

a = rzd.merge(auto, on = 'client_id', how = 'outer')
b = a.merge(air, on = 'client_id', how = 'outer').fillna(0)
b # таблица с тремя типами выручки для каждого client_id без указания адреса клиента

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           0.0          0.0
1        112       2810.0           0.0          0.0
2        113      10283.0       57483.0          0.0
3        114       5774.0          83.0          0.0
4        115        981.0         912.0         81.0
5        116          0.0        4834.0          4.0
6        117          0.0          98.0         13.0
7        118          0.0           0.0        173.0

In [28]:
c = b.merge(client_base, on = 'client_id', how = 'outer').fillna(0)
c # таблица по типам выручки с указанием адреса клиента

   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           0.0          0.0  Комсомольская 4
1        112       2810.0           0.0          0.0   Энтузиастов 8а
2        113      10283.0       57483.0          0.0  Левобережная 1а
3        114       5774.0          83.0          0.0          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          0.0        4834.0          4.0    Строителей 18
6        117          0.0          98.0         13.0  Панфиловская 33
7        118          0.0           0.0        173.0     Мастеркова 4